// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vzcjpfpbybgtvgcswgua.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ6Y2pwZnBieWJndHZnY3N3Z3VhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTQ1NDgsImV4cCI6MjA3Mzc5MDU0OH0.SVYAKv2R_5Tzk6mhnR5ICMn_-fVhS3fGRL8FUDJJCrI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});